# These are supported funding model platforms

github: sizzlebop
patreon: admin@pinkpixel.dev
ko_fi: sizzlebop
buy_me_a_coffee: pinkpixel
paypal: https://paypal.me/neogurumipatterns
venmo: https://venmo.com/u/sizzlebop

